--
-- PostgreSQL database dump
--

\restrict bqeBaUiieaGJ14MBg9USCTf0w39djPp9WT8heui8xsqaRLEle3kYhbU4pX7tBi3

-- Dumped from database version 16.14
-- Dumped by pg_dump version 16.14

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: app_user; Type: TABLE; Schema: public; Owner: appuser
--

CREATE TABLE public.app_user (
    id bigint NOT NULL,
    password character varying(255),
    username character varying(255)
);


ALTER TABLE public.app_user OWNER TO appuser;

--
-- Name: app_user_id_seq; Type: SEQUENCE; Schema: public; Owner: appuser
--

ALTER TABLE public.app_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.app_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: project; Type: TABLE; Schema: public; Owner: appuser
--

CREATE TABLE public.project (
    id bigint NOT NULL,
    is_archived boolean NOT NULL,
    is_public boolean NOT NULL,
    name character varying(255)
);


ALTER TABLE public.project OWNER TO appuser;

--
-- Name: project_files; Type: TABLE; Schema: public; Owner: appuser
--

CREATE TABLE public.project_files (
    project_id bigint NOT NULL,
    file_id character varying(255) NOT NULL,
    file_hash character varying(255) NOT NULL,
    index_time timestamp(6) with time zone,
    file_name character varying(255) NOT NULL
);


ALTER TABLE public.project_files OWNER TO appuser;

--
-- Name: project_id_seq; Type: SEQUENCE; Schema: public; Owner: appuser
--

ALTER TABLE public.project ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.project_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: project_user_access; Type: TABLE; Schema: public; Owner: appuser
--

CREATE TABLE public.project_user_access (
    project_id bigint NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.project_user_access OWNER TO appuser;

--
-- Name: project_user_admin; Type: TABLE; Schema: public; Owner: appuser
--

CREATE TABLE public.project_user_admin (
    project_id bigint NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.project_user_admin OWNER TO appuser;

--
-- Name: question; Type: TABLE; Schema: public; Owner: appuser
--

CREATE TABLE public.question (
    id bigint NOT NULL,
    answer oid,
    answer_time timestamp(6) with time zone,
    question oid,
    project_id bigint
);


ALTER TABLE public.question OWNER TO appuser;

--
-- Name: question_id_seq; Type: SEQUENCE; Schema: public; Owner: appuser
--

ALTER TABLE public.question ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.question_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: question_sources; Type: TABLE; Schema: public; Owner: appuser
--

CREATE TABLE public.question_sources (
    question_id bigint NOT NULL,
    sources character varying(255)
);


ALTER TABLE public.question_sources OWNER TO appuser;

--
-- Name: app_user app_user_pkey; Type: CONSTRAINT; Schema: public; Owner: appuser
--

ALTER TABLE ONLY public.app_user
    ADD CONSTRAINT app_user_pkey PRIMARY KEY (id);


--
-- Name: project_files project_files_pkey; Type: CONSTRAINT; Schema: public; Owner: appuser
--

ALTER TABLE ONLY public.project_files
    ADD CONSTRAINT project_files_pkey PRIMARY KEY (project_id, file_name);


--
-- Name: project project_pkey; Type: CONSTRAINT; Schema: public; Owner: appuser
--

ALTER TABLE ONLY public.project
    ADD CONSTRAINT project_pkey PRIMARY KEY (id);


--
-- Name: project_user_access project_user_access_pkey; Type: CONSTRAINT; Schema: public; Owner: appuser
--

ALTER TABLE ONLY public.project_user_access
    ADD CONSTRAINT project_user_access_pkey PRIMARY KEY (project_id, user_id);


--
-- Name: project_user_admin project_user_admin_pkey; Type: CONSTRAINT; Schema: public; Owner: appuser
--

ALTER TABLE ONLY public.project_user_admin
    ADD CONSTRAINT project_user_admin_pkey PRIMARY KEY (project_id, user_id);


--
-- Name: question question_pkey; Type: CONSTRAINT; Schema: public; Owner: appuser
--

ALTER TABLE ONLY public.question
    ADD CONSTRAINT question_pkey PRIMARY KEY (id);


--
-- Name: project_user_access fk1xumutp842h1bnxmm0vktcmw1; Type: FK CONSTRAINT; Schema: public; Owner: appuser
--

ALTER TABLE ONLY public.project_user_access
    ADD CONSTRAINT fk1xumutp842h1bnxmm0vktcmw1 FOREIGN KEY (project_id) REFERENCES public.project(id);


--
-- Name: question_sources fk94la1bg0325xy9sqwe5bdp3e8; Type: FK CONSTRAINT; Schema: public; Owner: appuser
--

ALTER TABLE ONLY public.question_sources
    ADD CONSTRAINT fk94la1bg0325xy9sqwe5bdp3e8 FOREIGN KEY (question_id) REFERENCES public.question(id);


--
-- Name: project_files fkdtg02hcpullxjybevxd9wimmj; Type: FK CONSTRAINT; Schema: public; Owner: appuser
--

ALTER TABLE ONLY public.project_files
    ADD CONSTRAINT fkdtg02hcpullxjybevxd9wimmj FOREIGN KEY (project_id) REFERENCES public.project(id);


--
-- Name: project_user_admin fkffyo21lg38rf1ns8i3q45ggsv; Type: FK CONSTRAINT; Schema: public; Owner: appuser
--

ALTER TABLE ONLY public.project_user_admin
    ADD CONSTRAINT fkffyo21lg38rf1ns8i3q45ggsv FOREIGN KEY (user_id) REFERENCES public.app_user(id);


--
-- Name: question fkjm6odncdmkljsusqjoex1l2ug; Type: FK CONSTRAINT; Schema: public; Owner: appuser
--

ALTER TABLE ONLY public.question
    ADD CONSTRAINT fkjm6odncdmkljsusqjoex1l2ug FOREIGN KEY (project_id) REFERENCES public.project(id);


--
-- Name: project_user_admin fkptoyhv7b42kl5ida9wkwtlcs; Type: FK CONSTRAINT; Schema: public; Owner: appuser
--

ALTER TABLE ONLY public.project_user_admin
    ADD CONSTRAINT fkptoyhv7b42kl5ida9wkwtlcs FOREIGN KEY (project_id) REFERENCES public.project(id);


--
-- Name: project_user_access fksa6i1iwneqfu8f69439w7ockn; Type: FK CONSTRAINT; Schema: public; Owner: appuser
--

ALTER TABLE ONLY public.project_user_access
    ADD CONSTRAINT fksa6i1iwneqfu8f69439w7ockn FOREIGN KEY (user_id) REFERENCES public.app_user(id);


--
-- PostgreSQL database dump complete
--

\unrestrict bqeBaUiieaGJ14MBg9USCTf0w39djPp9WT8heui8xsqaRLEle3kYhbU4pX7tBi3

