spring:
  application:
    name: mainApp
  config:
    import: optional:file:.env[.properties]
  http:
    client:
      connect-timeout: 120s
      read-timeout: 120s
  elasticsearch:
    uris: http://localhost:9200
  #    username: <elasticsearch username>
  #    password: <elasticsearch password>
  ai:
    openai:
      chat:
        options:
          model: qwen3:latest
          temperature: 0.7
          http-headers:
            Authorization: Basic ${OLLAMACREDENTIALS} # needs to be set by the user
        base-url: https://ai-dev.smartarch.cz/ollama/
      embedding:
        base-url: http://localhost:11434 # It seems that none of the models from smartarch can do embedding
        options:
          model: hf.co/second-state/All-MiniLM-L6-v2-Embedding-GGUF:latest
      api-key: o
    vectorstore:
      elasticsearch:
        initialize-schema: true
        index-name: async-index
        dimensions: 384
        similarity: cosine