package cz.cuni.mff.hanaf.mainapp.llm;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.ai.chat.prompt.SystemPromptTemplate;
import org.springframework.ai.ollama.api.OllamaApi;
import org.springframework.ai.ollama.api.OllamaOptions;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.core.io.Resource;

import java.util.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.stream.Collectors;

public class Qwen3Methods implements LlmMethods {
    private final OllamaApi ollamaApi;

    @Value("classpath:/prompts/check-relevance.txt")
    private Resource systemResource;

    public Qwen3Methods(OllamaApi ollamaApi) {
        this.ollamaApi = ollamaApi;
    }
    /**
     * Takes the answer generated by the LLM and returns it in the format expected by the frontend
     * @param answer The answer generated by the LLM
     * @return The information from the answer in a map with the answer, sources, and done keys
     */
    @Override
    public Map<String, Object> prepareAnswer(String answer) {
        System.out.println("temp");
        System.out.println(answer); // todo test remove in future
        System.out.println("endTemp");

        answer = this.removeThinking(answer);
        Map<String, Object> result = new HashMap<>();
        result.put("answer", answer);
        result.put("done", true);

        try {
            ObjectMapper objectMapper = new ObjectMapper();
            String jsonOutput = objectMapper.writerWithDefaultPrettyPrinter()
                    .writeValueAsString(result);
            System.out.println(jsonOutput);
        } catch (JsonProcessingException e) {
            e.printStackTrace();
        }

        return result;
    }

    /**
     * Checks if the given document is relevant to the query
     * @param document The given document
     * @param query The given query
     * @return true if the document is relevant, false otherwise
     */
    @Override
    public boolean verifySource(String document, String query) {
        SystemPromptTemplate promptTemplate = new SystemPromptTemplate(systemResource);

        String prompt = promptTemplate.render(Map.of(
                "query", query,
                "document", document));
        String result = callWithoutThinking(prompt);
        System.out.println(result + " done");
        return result != null && result.trim().equalsIgnoreCase("yes");

    }

    /**
     * Removes the thought process from the given output
     *
     * @param withThinking The output of the LLM with the thought process
     * @return The output of the LLM without the thought process
     */
    private String removeThinking(String withThinking) {
        Pattern pattern = Pattern.compile("<think>.*?</think>", Pattern.DOTALL);
        Matcher matcher = pattern.matcher(withThinking);
        return matcher.replaceFirst("");
    }

    private String callWithoutThinking(String prompt) {
        Map<String, Object> options = OllamaOptions.builder()
                .model("qwen3:0.6b")
                .temperature(0.7)
                .build()
                .toMap();

        options.put("think", false);

        OllamaApi.ChatRequest request = OllamaApi.ChatRequest.builder("qwen3:0.6b")
                .stream(false)
                .messages(List.of(
                        OllamaApi.Message.builder(OllamaApi.Message.Role.USER)
                                .content(prompt)
                                .build()))
                .options(options)
                .build();

        return ollamaApi.chat(request).message().content();
    }
}
