package cz.cuni.mff.hanaf.core.llm;

import org.springframework.ai.chat.prompt.SystemPromptTemplate;
import org.springframework.core.io.Resource;

import java.util.Map;

public interface LlmMethods {

    /**
     * Takes the answer generated by the LLM and returns it in the format expected by the frontend
     * @param answer The answer generated by the LLM
     * @return The information from the answer in a map with the answer, sources, and done keys
     */
    default String prepareAnswer(String answer) {
        System.out.println("temp");
        System.out.println(answer); // todo test remove in future
        System.out.println("endTemp");

        answer = this.removeThinking(answer);
        return answer;
    }

    /**
     * Checks if the given document is relevant to the query
     * @param document The document to check
     * @param query The query the document is meant to answer
     * @return True if the query is relevant, false otherwise
     */
    default boolean verifySource(String document, String query) {
        SystemPromptTemplate promptTemplate = new SystemPromptTemplate(getResource());

        String prompt = promptTemplate.render(Map.of(
                "query", query,
                "document", document));
        String result = callWithoutThinking(prompt);
        System.out.println(result + " done");
        return result != null && result.trim().equalsIgnoreCase("yes");
    }

    Resource getResource();

    String removeThinking(String withThinking);

    String callWithoutThinking(String prompt);
}
