package cz.cuni.mff.hanaf.core.llm;

import org.springframework.ai.chat.prompt.SystemPromptTemplate;
import org.springframework.core.io.Resource;

import java.util.Map;

/**
 * Defines the core capabilities and utility methods for interacting with Large Language Models.
 */
public interface LlmMethods {

    /**
     * Takes the answer generated by the LLM and returns it in the format expected by the frontend.
     *
     * @param answer the answer generated by the LLM
     * @return the answer as a string
     */
    default String prepareAnswer(String answer) {
        answer = this.removeThinking(answer);
        return answer;
    }

    /**
     * Checks if the given document is relevant to the query.
     *
     * @param document the document to check
     * @param query the query the document is meant to answer
     * @return {@code true} if the query is relevant, {@code false} otherwise
     */
    default boolean verifySource(String document, String query) {
        SystemPromptTemplate promptTemplate = new SystemPromptTemplate(getResource());

        String prompt = promptTemplate.render(Map.of(
                "query", query,
                "document", document));
        String result = callWithoutThinking(prompt);
        System.out.println(result + " done");
        return result != null && result.trim().toLowerCase().contains("yes");
    }

    /**
     * Returns the prompt template resource used for source verification.
     *
     * @return the verification prompt template resource
     */
    Resource getResource();

    /**
     * Removes the thought process from the given output.
     *
     * @param withThinking the output of the LLM with the thought process
     * @return the output of the LLM without the thought process
     */
    String removeThinking(String withThinking);

    /**
     * Calls an LLM with disabled thinking.
     *
     * @param prompt the prompt text to send to the LLM
     * @return the response text from the LLM
     */
    String callWithoutThinking(String prompt);
}
